### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by andrekampert** [Product-Foundry/akka-persistence-couchbase#6]
```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658) ~[na:1.8.0_45]
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[na:1.8.0_45]
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[na:1.8.0_45]
	at com.couchbase.client.deps.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:645) ~[core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:228) ~[core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.buffer.PoolArena.allocate(PoolArena.java:212) ~[core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.buffer.PoolArena.allocate(PoolArena.java:132) ~[core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:271) ~[core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155) ~[core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146) ~[core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:107) ~[core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl.allocate(AdaptiveRecvByteBufAllocator.java:104) ~[core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117) ~[core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [core-io-1.2.4.jar:na]
	at com.couchbase.client.deps.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [core-io-1.2.4.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by andrekampert** [comment]
Seems to happen only under heavy load conditions, in which case snapshots can also be created
